[workspace]
members = [
    "binary",
    "net",
    "protocol",
    "concierge",
    "server",
    "example_server",
    "sticky",
    "command",
    "command_derive",
    "text_component",
    "minecraft_constants",
    "magma"
]