[package]
name = "graphite_minecraft"
version = "0.1.0"
edition = "2021"
license-file = "LICENSE"
description = "Library for crafting high-performance Minecraft servers"
homepage = "https://github.com/Moulberry/Graphite"
repository = "https://github.com/Moulberry/Graphite"
readme = "README.md"

exclude = [
    "example_server/*",
]

[dependencies]
graphite_server = { path = "crates/graphite_server" }
graphite_concierge = { path = "crates/graphite_concierge" }
graphite_net = { path = "crates/graphite_net" }
graphite_mc_protocol = { path = "crates/graphite_mc_protocol" }
graphite_mc_constants = { path = "crates/graphite_mc_constants" }

# These two can be behind feature flag
graphite_command = { path = "crates/graphite_command" }
graphite_magma = { path = "crates/graphite_magma" }

[workspace]
members = [
    "crates/*",
    "example_server"
]