[package]
name = "text_component_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
anyhow = "1.0.57"
proc-macro2 = "1.0.40"
syn = { version = "1.0.98", features = ["parsing", "extra-traits"] }
quote = "1.0.20"